@ComputerStorageSolutions_HostAddress = http://localhost:5037

GET {{ComputerStorageSolutions_HostAddress}}/ComputerStorageSolutions/
Accept: application/json

###

POST {{ComputerStorageSolutions_HostAddress}}/api/Login
Content-Type:application/json

{
  "Email":"Test@gamil.com",
  "Password": "Test@123"
}

###
GET {{ComputerStorageSolutions_HostAddress}}/api/Products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiNjIyYTEyMzItMGVlMC00MDFlLTg3NzAtMWM4MGM0MmYxZDgxIiwiVXNlcklkIjoiOTUyMDBlZjAtMGFmOS00N2FiLTE4NzgtMDhkY2M4MmU3ZTg2IiwiRW1haWwiOiJUZXN0QGdhbWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzI0OTQyMDc5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMzciLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMzcifQ.gDCyADp_GmACuoM-Rb9NjM1SoX0gAV2r_FxMjvAGGc3884Dp7ykLbkJVcX3JLW-Pr_gwVYEZ0Mw0TzbMMQtcXQ

###
PATCH {{ComputerStorageSolutions_HostAddress}}/api/Products/ModifyProduct
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiZDRlNWJkNDQtODU1MS00MGQ2LTk0MTktZWI4YmVhMzk5YmQ5IiwiVXNlcklkIjoiYTI4ODdmNDQtNGY0Ni00MTk2LThiNjEtYmFkMGU0NmRmN2Q5IiwiRW1haWwiOiJqYW5lZG9lQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6Ijk2YWM4ZDEyLWI2MzEtNDYzOC1hOWM2LWM0ODU2MGFmNDk5MSIsImV4cCI6MTcyNDM5OTQ0MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM3IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDM3In0.Ovf61dFVFjDzQVDdO5Rk0Yupt5hrD1ciJiNu3xsgSlviw7Lv9yPUyQcjsHVXjIZfUyjcYF0csYhz2R3f-CjNsw
Content-Type:application/json

{
  "productId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "productName": "500GB HDD",
  "categoryId": 2,
  "description": "Affordable HDD with 500GB capacity",
  "price": 25,
  "stockQuantity": 25,
  "imageUrl": "/images/500gb_hdd.png",
  "status": "NotAvailable"
}
